"""empty message

Revision ID: a0288b333c21
Revises: 
Create Date: 2022-10-03 10:08:11.400535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0288b333c21"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_opportunity", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("cpf"),
    )
    op.create_table(
        "car",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("owner_cpf", sa.String(length=11), nullable=False),
        sa.Column("color", sa.String(length=6), nullable=False),
        sa.Column("model", sa.String(length=11), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_cpf"],
            ["client.cpf"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("car")
    op.drop_table("client")
    # ### end Alembic commands ###
